# Desafío - Regresión desde el aprendizaje de máquinas

## Esteban Gonzalez Amigo

## Desafío 1: Prepare el ambiente de trabajo
- Importe las librerías básicas para el análisis de datos.
- Importe el módulo linear_model , y las funciones mean_squared_error , r2_score y train_test_split .
- Importe la base de datos boston.csv y elimine la columna Unnamed: 0 .
- Obtenga las medidas descriptivas de la base de datos con .describe() .

In [1]:
import warnings
warnings.filterwarnings('ignore')
import pandas as pd
import numpy as np
from scipy import stats
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm
import statsmodels.formula.api as smf

from sklearn import linear_model


from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import train_test_split

plt.style.use('seaborn-whitegrid')
plt.rcParams['figure.figsize'] =(10, 6)

In [2]:
df= pd.read_csv('Boston.csv').drop('Unnamed: 0', axis=1)

In [3]:
df.describe()

crim          zn       indus        chas         nox          rm  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean     3.613524   11.363636   11.136779    0.069170    0.554695    6.284634   
std      8.601545   23.322453    6.860353    0.253994    0.115878    0.702617   
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.082045    0.000000    5.190000    0.000000    0.449000    5.885500   
50%      0.256510    0.000000    9.690000    0.000000    0.538000    6.208500   
75%      3.677082   12.500000   18.100000    0.000000    0.624000    6.623500   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

              age         dis         rad         tax     ptratio       black  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    68.574901    3.795043    9.549407  408.237154   18.455534  356.674032   
std     28.148861    2.105710    8.707259  168.537116    2.164946   91.294864   
min      2.900000    1.129600    1.000000  187.000000   12.600000    0.320000   
25%     45.025000    2.100175    4.000000  279.000000   17.400000  375.377500   
50%     77.500000    3.207450    5.000000  330.000000   19.050000  391.440000   
75%     94.075000    5.188425   24.000000  666.000000   20.200000  396.225000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            lstat        medv  
count  506.000000  506.000000  
mean    12.653063   22.532806  
std      7.141062    9.197104  
min      1.730000    5.000000  
25%      6.950000   17.025000  
50%     11.360000   21.200000  
75%     16.955000   25.000000  
max     37.970000   50.000000

## Desafío 2: División de la muestra
- Genere conjuntos de entrenamiento y validación con train_test_split .
- Genere segmentaciones del 33% para las muestras de validación.
- Incluya una semilla pseudoaleatoria

In [4]:
df_copia = df.copy()

y_vec = df_copia.loc[:,'medv']
x_mat = df_copia.loc[:,'crim':'lstat']

x_train, x_test, y_train, y_test = train_test_split(x_mat, y_vec, test_size =.33, random_state= 11238)

## Desafío 3: Generación de modelos
- Ahora implementaremos dos versiones del modelo lineal:
    - Con intercepto y atributos normalizados.
    - Sin intercepto y atributos no normalizados.
- Cada versión debe generarse en un nuevo objeto inicializado.
- Posteriormente se deben entrenar los modelos especificando la matriz y vector de entrenamiento.
- Con los modelos entrenados, genere una predicción de matriz de validación.

In [5]:
modelo = linear_model.LinearRegression(fit_intercept=True, normalize=True)

#modelo train
modelo.fit(x_train, y_train)

#modelo predicho
modelo_yhat = modelo.predict(x_test)

modelo_yhat

array([ 3.05315878e+01,  2.47509314e+01,  1.98103846e+01,  1.74228233e+01,
        2.25097011e+01,  2.70581758e+01,  2.27794388e+01,  2.87158252e+01,
        2.31071985e+01,  1.57602374e+01,  3.08889617e+01,  2.21239020e+01,
        2.10752936e+01,  2.74150439e+01,  1.92712447e+01,  1.88343331e+01,
        2.98851489e+01,  2.50525300e+01,  2.01623234e+01,  1.71084839e+01,
        1.27629436e+01,  2.62957895e+01,  1.31452754e+01,  1.69603810e+01,
        2.03018537e+01,  3.14808910e+01,  2.46209742e+01,  1.53831297e+01,
        2.03314108e+01,  1.73322921e+01,  1.67194707e+01,  2.01267261e+01,
        2.76940059e+01,  1.82123698e+01,  1.13458379e+01,  2.31696468e+01,
        2.36044692e+01,  1.33813887e+01,  3.34363855e+01,  2.88412473e+01,
        1.46399803e+01,  2.07905064e+01,  3.32569220e+01,  2.54876889e+01,
        2.28698204e+01,  3.52876019e+01,  2.18014403e+01,  2.66370600e+01,
        2.86293835e+01,  2.55062741e+01,  2.00705471e+01,  2.42681654e+01,
        1.89254216e+01,  

In [6]:
modelo_sin = linear_model.LinearRegression(fit_intercept=False, normalize=False)

#modelo train
modelo_sin.fit(x_train, y_train)

#modelo predicho
modelo_sin_yhat = modelo_sin.predict(x_test)

modelo_sin_yhat

array([29.73800187, 22.44563267, 21.65888321, 17.68558194, 21.81107521,
       26.26406006, 24.14449212, 27.92764272, 26.38722571, 18.55646924,
       30.69505765, 21.09043413, 21.27463189, 26.90444757, 19.13893758,
       18.3236963 , 30.9126002 , 25.36492171, 21.1083799 , 18.53905325,
       13.7354785 , 24.93742552, 13.43840824, 17.95423134, 20.73604273,
       31.05098143, 24.78180479, 15.04101684, 22.09414355, 19.47982552,
       18.06430259, 19.79934425, 27.00193991, 19.7348754 , 11.90445514,
       22.39645955, 25.29917717, 15.9635396 , 32.5969429 , 30.18422243,
       11.40429796, 20.11958314, 32.20809619, 22.63540588, 25.91493132,
       35.09560325, 20.98802851, 28.03057409, 27.75630633, 25.8394719 ,
       20.80481176, 25.15316284, 20.28313381, 20.4115492 , 22.12846452,
       15.94892859, 21.79763238, 24.68046034, 22.67055216, 23.36702254,
       21.74813572, 17.70028931, 25.53843526, 14.92039121, 19.09049717,
       43.09443879, 10.58269771, 16.15938287, 25.67969744, 29.37

## Desafío 4: Obtención de métricas
- Ahora generemos una función llamada report_scores que ingrese como argumentos el vector de datos predichos y el vector de datos por validar.
- La función debe imprimir las métricas del Error Cuadrático Promedio y R2.
- Reporte las métricas para ambos modelos. En base a ello, seleccione el mejor modelo

In [7]:
def repost_scores(model_yhat,v_x_valid):
    print('El error cuadratico es: ', mean_squared_error(v_x_valid, model_yhat))
    print('El valor R2 es: ', r2_score(v_x_valid, model_yhat))

In [8]:
repost_scores(modelo_yhat, y_test)

El error cuadratico es:  30.697831517740727
El valor R2 es:  0.6005199127106764


In [9]:
repost_scores(modelo_sin_yhat, y_test)

El error cuadratico es:  34.26939996145279
El valor R2 es:  0.5540420215010208


In [10]:
# el mejor r2 debe ser mayor
# el mejor error cuadratico es el menor

# Desafío 5: Refactorización del modelo
- Genere una función llamada fetch_features que ingrese como argumentos la base de datos y el nombre del vector objetivo. El nombre del vector debe ser medv por defecto
- La función debe retornar una lista con las correlaciones entre cada atributo y el vector objetivo y su nombre.
- Reporte brevemente cuales los 6 atributos con una mayor correlación con medv


In [11]:
def fetch_features(df, medv):
    columns = df.columns
    attr_name, pearson_r, abs_pearson_r = [], [], []

    for col in columns:
        if col != medv:
            attr_name.append(col)
            pearson_r.append(df[col].corr(df[medv]))
            abs_pearson_r.append(abs(df[col].corr(df[medv])))

    features = pd.DataFrame(
        {'attribute': attr_name,
        'corr': pearson_r,
        'abs_corr': abs_pearson_r}
    )

    features= features.set_index('attribute')
    tabla = features.sort_values(by=['abs_corr'], ascending= False)
    
    print(attr_name)
    print(pearson_r)
    print(abs_pearson_r)
    
    return tabla.head(6)

In [12]:
fetch_features(df_copia, 'medv')

['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax', 'ptratio', 'black', 'lstat']
[-0.38830460858681154, 0.3604453424505432, -0.4837251600283729, 0.17526017719029843, -0.4273207723732826, 0.6953599470715393, -0.3769545650045963, 0.24992873408590388, -0.381626230639778, -0.4685359335677669, -0.5077866855375621, 0.33346081965706637, -0.7376627261740151]
[0.38830460858681154, 0.3604453424505432, 0.4837251600283729, 0.17526017719029843, 0.4273207723732826, 0.6953599470715393, 0.3769545650045963, 0.24992873408590388, 0.381626230639778, 0.4685359335677669, 0.5077866855375621, 0.33346081965706637, 0.7376627261740151]


corr  abs_corr
attribute                    
lstat     -0.737663  0.737663
rm         0.695360  0.695360
ptratio   -0.507787  0.507787
indus     -0.483725  0.483725
tax       -0.468536  0.468536
nox       -0.427321  0.427321

## Desafío 6: Refactorización del modelo predictivo
- Genere otros conjuntos de entrenamiento y validación en base a una matriz con los 6 atributos identificados y el vector objetivo.
- Entrene un modelo en base al mejor desempeño.
- Reporte las métricas para el nuevo modelo.


In [13]:
y_vec2=df['medv']

x_mat2=df.loc[:,['lstat', 'rm', 'ptratio', 'indus', 'tax', 'nox']]

In [14]:
## se hace toodo de nuevo

In [15]:
x_train2, x_test2, y_train2, y_test2 = train_test_split(x_mat2, y_vec2, test_size =.33, random_state= 11238)

In [20]:
modelo_3 = linear_model.LinearRegression(fit_intercept = True, normalize = True)
modelo_3_train = modelo_3.fit(x_train2, y_train2)
modelo_3_yhat = modelo_3.predict(x_test2)

print("Modelo 3")
print("La cantidad de predicciones realizadas en x_test son: ", len(modelo_3_yhat), "\n")
print("las predicciones son: \n",  modelo_3_yhat)

Modelo 3
La cantidad de predicciones realizadas en x_test son:  167 

las predicciones son: 
 [31.7154155  24.86653591 21.61377952 19.49294024 21.2161735  26.13967462
 25.08101932 28.79999134 23.52759539 20.90434083 28.3738251  22.58028404
 19.46077415 28.04063226 17.67793017 19.49272448 31.2664637  25.42080231
 23.23468695 17.14740981 15.10293691 24.99615742 16.15015849 15.50423755
 20.78768924 32.65013017 24.77688799 18.86346762 18.39245434 16.89961266
 18.09143602 19.26992544 26.08310975 17.46071904 13.54108939 22.78144451
 23.80352985 18.2991265  31.82150031 31.05867465 18.32267256 19.76828209
 34.65560416 27.0308222  28.1548651  33.92956697 23.00042356 29.42845064
 29.10995088 25.86561102 19.07713735 27.6824574  17.12353655 15.86969425
 22.5138358  17.92516194 24.62439942 19.65164806 22.76785078 24.7127325
 19.51239488 14.49680611 25.62624888 14.34669708 21.01931291 36.21089149
 14.06228619 17.086307   27.60304903 30.74500657 19.93749419 16.98147604
 32.55282249 26.09733132 36.813

In [21]:
prom_error_cuadratico_3 = mean_squared_error(y_test2, modelo_3_yhat).round(1)
r_cuadrado_3 = r2_score(y_test2, modelo_3_yhat).round(2)

print("Promedio del error cuadrático: ", prom_error_cuadratico_3)
print("R-cuadrado: ", r_cuadrado_3)

Promedio del error cuadrático:  37.5
R-cuadrado:  0.51


## Desafío 7: Predicción de casos
- A continuación se generaron dos arrays que representan el peor escenario posible ( worst_neighbor ) y el mejor escenario posible ( best_neighbor ).
- Ingrese los arrays en el modelo entrenado y reporte cuál sería el valor esperado dada las condiciones.

In [23]:
worst_neighbor = np.array([37.9, 12.6, 3.5, 27.7, 187, 0.87]).reshape(1,-1)
best_neighbor = np.array([1.73, 22, 8.7, 0.46, 711, 0.38]).reshape(1,-1)

modelo_worst_yhat = modelo_3.predict(worst_neighbor)
modelo_best_yhat = modelo_3.predict(best_neighbor)

modelo_worst_yhat, modelo_best_yhat

(array([59.97435265]), array([118.55978502]))